title: Cameron Bronstein
description: Remote Sensing, Machine Learning, Ecology
logo: assets/img/backpacking.jpg
theme: jekyll-theme-minimal
email: cambostein@gmail.com
github-profile: https://github.com/cameronbronstein